
author: 'llazon'
title: 'All Things AWS'
description: 'Notes and ramblings all about Amazon Web Services (AWS)!'

# If you clone the Minima repo and build locally, use this setting.
#theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
remote_theme: jekyll/modernist

plugins:
  - jekyll-feed
  - jekyll-seo-tag

